site_name: py-bugger

repo_url: https://github.com/ehmatthes/py-bugger/

markdown_extensions:
  - attr_list
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: false
  - def_list
  - admonition
  - pymdownx.details
  - footnotes

nav:
  - "Introduction": "index.md"
  - "Quick Start": "quick_start/index.md"
  - "Usage": "usage/index.md"
  - "Contributing":
    - "contributing/index.md"
    - "Roadmap": "contributing/roadmap.md"
  - "Maintaining": "maintaining/index.md"

theme: 
  name: material
  features:
    - navigation.indexes